### ISSUE TITLE
[ErrorException] Undefined Variable: table

### ISSUE THREAD

**Issue by Srijan-Karki** [briankiewel/pagodabox-laravel-4#24]
I have defined the variable. But i can't fix the problem. Others file migrate except this one.
I was learning from the video.. It works there but not in my laptop.
Here is the code:

<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateNewArticlesTable extends Migration {
    public function up()
    {
        Schema::create('articles', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title');
            $table->text('body');
            $table->timestamps();
            $table->timestamp('published_at');
        });
    }
    public function down()
    {
        Schema::drop('articles');
    }
}

**Comment by briankiewel** [comment]
There's nothing wrong with that migration, I'd look closely at all of your other ones. If you want to post the others here I can take a look.

**Comment by Srijan-Karki** [comment]
Ok Here are the others files that migrated. However, the error notification was still there.
These both are the codes generated by artisan. Yet, this one works but the previous one doesnot.
<?php
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUsersTable extends Migration{
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('username');
            $table->string('email')->unique();
            $table->string('password', 60);
            $table->rememberToken();
            $table->timestamps();
        });
    }

```
public function down()
{
    Schema::drop('users');
}
```

}

This one was generated by laravel itself and it also works.

<?php
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePasswordResetsTable extends Migration{
    public function up()
    {
        Schema::create('password_resets', function (Blueprint $table) {
            $table->string('email')->index();
            $table->string('token')->index();
            $table->timestamp('created_at');
        });
    }

```
public function down()
{
    Schema::drop('password_resets');
}
```

}

**Comment by briankiewel** [comment]
That migration looks ok as well. Are you sure you have no other migrations anywhere else? Both of these work fine for me. 

Try running `artisan clear-compiled` and see if that helps. If that doesn't help, I would also try removing all of your migrations and add them back one by one making sure each one works as you add it back in. This way you can identify where exactly the problem is.

**Comment by Srijan-Karki** [comment]
I will try that. Thank You.

**Comment by Srijan-Karki** [comment]
I tried, but it doesn't work. I have deleted all data from MySQL manually. Then i ran those files. And only the table users and password_reset migrates. The articles table doesn't migrate. Even another auto-generated migration table is displaying error.

**Comment by Srijan-Karki** [comment]
I fixed it. Thanks. There was another file in that folder which was generating all those errors.
